### ISSUE TITLE
openssl: undefined symbol: SSLv2_server_method

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#51]
When I run:

```bash
root [ ~ ]# python
Python 2.7.10 (default, Oct 29 2015, 19:56:25) 
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt4 import QtNetwork
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib64/libQtNetwork.so.4: undefined symbol: SSLv2_server_method
>>> 
```

Could be a problem with the resent openssl update?

I recompiled the previous openssl version: `version=1.0.2e` which solved the problem

```bash
root [ ~ ]# python
Python 2.7.10 (default, Oct 29 2015, 19:56:25) 
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt4 import QtNetwork
>>> 
```

Searching google for: 
http://lmgtfy.com/?q=ImportError%3A+%2Fusr%2Flib64%2FlibQtNetwork.so.4%3A+undefined+symbol%3A+SSLv2_server_method shows a couple of recent issues.

**Comment by tnut** [comment]
Because of this, Pierre and I decides to accelerate the release of the next version 8.1 
It was not suppose to break python package and most probably others as well. This was a security update...
Unfortunatly, it's not really a good idea to go back to previous release (openssl 1.0.2e) as python have been updated and recompiled to fix this issue and to permit the compilation of firefox 45.0

This all stuf demonstrate one thing: Rolling release sucks

status of today: Collections base, base-extra, cli completed (means recompiled). 
They is a new ISO available for test and mainly to validate the new  4.4.X LTS kernel on NuTyX
Hopefully, this week we can have xfce4, kde5 already availables on 8.1 base system

**Comment by peter1000** [comment]
Thanks not sure if I should close the issue or you do it when 8.1 is release. Probably best you do it as you see fit.

**Comment by tnut** [comment]
We beter leave it open, at least people  can be informed

**Comment by tnut** [comment]
http://lists.linuxfromscratch.org/pipermail/blfs-dev/2016-March/031795.html
